#ifndef CONFIG_H
#define CONFIG_H

// mouse
#define MOUSEKEY_MOVE_DELTA 4
#define MMOUSEKEY_MAX_SPEED	0

// encoders
#define NUM_ENCODERS 1
#define ENCODERS_PAD_A { GP21 }
#define ENCODERS_PAD_B { GP22 }
#define ENCODER_RESOLUTION 4


// backlight
#define BACKLIGHT_PWM_DRIVER PWMD5
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define BACKLIGHT_ON_STATE 1
//#define BACKLIGHT_PWM_FREQUENCY 40000
#endif
